### PR TITLE
fix(docs): add display time at the bottom of each page

### PR DESCRIPTION
**Pull request by JulienMassonnat**
Wouldn't it be a good idea to add the update date at the bottom of each page? The functionality is natively present in docusaurus and only needs to be activated. Is that ok with you?

image

## Summary by CodeRabbit

- **Documentation**
	- Updated the documentation site to display the last update time of pages.
	- Enhanced the footer with a new `Tools` section for better navigation and resource access.

### CODE REVIEW

**Review by MdechampG — APPROVED** [review]
Good idea 👍🏻

**Review by ccamel — APPROVED** [review]
That's great! Thanks :heart:

**Comment by emmanuelaldeguer** [comment]
👌

**Comment by JulienMassonnat** [comment]
I think we need some improvements because the date is the same on every pages...
I need to dig deeper this issue : https://github.com/facebook/docusaurus/issues/2798

**Comment by JulienMassonnat** [comment]
The solution seems to be inside the Github Pages configuration 
image
@ccamel could you provide some help ? Thanks

**Comment by ccamel** [comment]
@JulienMassonnat Got it. I'll make that tweak right away.

**Pull request merged**
