### PR TITLE
Feat/add knowledge graph

### PR DESCRIPTION
**Pull request by ccamel**
Add a knowledge graph example.

The knowledge graph is generated using [graphviz](https://graphviz.org/) used as a [react component](https://www.npmjs.com/package/graphviz-react) in the [MDX](https://mdxjs.com) files. A basic style has been applied, but will be reviewed when we have an "official" palette.

**Dark theme**
image

**Light theme**
image

### CODE REVIEW

**Comment by ccamel** [comment]
@fredericvilcot Can you take a look at the PR, I'd like to pass it quickly to avoid conflicts.

What I will add (and currently missing) is:
- fixing the fonts of the text
- put the description of the graph in a separate file (not in the markdown) at

**Comment by fredericvilcot** [comment]
@ccamel 
I pushed a commit that includes: 

- minor code fixes
- some `padding` (top/bottom) for the main content
- new `transform` rule to align correctly right part of the arrows with geometric elements
- new `Barlow` font for `text` elements

**Comment by fredericvilcot** [comment]
@ccamel 
Here are the animations: 
**Dark theme**
https://user-images.githubusercontent.com/47554752/174082539-e2d4bd03-cb2d-41cb-8cc2-deb7b0366e1a.mov

**Light theme**
https://user-images.githubusercontent.com/47554752/174082419-ac1b2c23-0311-41d3-a830-4bab1fd55af8.mov

**Comment by ccamel** [comment]
Thanks all for your contribution (@fredericvilcot, @JulienMassonnat, @SonnevilleDamien) ❤️

**Pull request merged**
