### PR TITLE
Feat/add faq entry

### PR DESCRIPTION
**Pull request by ccamel**
Add the `FAQ` entry.

We can adjust if necessary. Just let me know.

image

### CODE REVIEW

**Review by JulienMassonnat — COMMENTED** [review]
Q&A or F.A.Q. ?

**Comment by ccamel** [comment]
> Q&A or F.A.Q. ?

It's up to you 😌

**Review by fredericvilcot — APPROVED** [review]
LGTM!

**Review by tpelliet — CHANGES_REQUESTED** [review]
FAQ please :pray:

**Review by MdechampG — APPROVED** [review]

**Review by tpelliet — APPROVED** [review]

**Review by amimart — APPROVED** [review]

**Pull request merged**
