### PR TITLE
fix: update url use cases

### PR DESCRIPTION
**Pull request by jeremylgn**
Self explanatory

### CODE REVIEW

**Review by ccamel — CHANGES_REQUESTED** [review]
Be sure to commit all the changes. From what I see, there's only an addition, and not a rename (which is problematic because the old file is still there).

image

**Comment by jeremylgn** [comment]
> Be sure to commit all the changes. From what I see, there's only an addition, and not a rename (which is problematic because the old file is still there).
> image

In fact, I renamed the file directly.
Then I added it

image
image

**Comment by ccamel** [comment]
> In fact, I renamed the file directly. Then I added it

You have to add & commit the old file as well. From what I see, your directory is not clean for this reason.

**Review by ccamel — APPROVED** [review]
:+1:

**Review by JulienMassonnat — APPROVED** [review]

**Pull request merged**
