### PR TITLE
chore: add matomo usage tracking

### PR DESCRIPTION
**Pull request by jeremylgn**
Add web analytics to the [Docusaurus website](https://docs.okp4.network/) web site using [matomo](https://matomo.org/).

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
Thanks! 👍

**Review by fredericvilcot — APPROVED** [review]
I guess that's a snippet provided by `matamo` documentation but we should consider improving the syntax soon...

**Comment by ccamel** [comment]
@fredericvilcot yes, this is the snippet provided by matomo, copied and pasted as is, with some formatting. Of course we can consider improving the syntax a bit. I'll let you be the judge.

**Comment by fredericvilcot** [comment]
> @fredericvilcot yes, this is the snippet provided by matomo, copied and pasted as is, with some formatting. Of course we can consider improving the syntax a bit. I'll let you be the judge.

@ccamel 
Let's merge it as `docusaurus` targets `es5`, we'll see later 😌

**Review by amimart — APPROVED** [review]

**Comment by ManonPoint26** [comment]
It works ☺️!

**Pull request merged**
