### PR TITLE
Feat/governance

### PR DESCRIPTION
**Pull request by ccamel**
This PR adds introductory technical elements on Governance, taken from the various blog articles that have been written on the subject so far.

### CODE REVIEW

**Review by MdechampG — COMMENTED** [review]
Thank you @ccamel ! Here are some propositions to improve.

**Comment by ccamel** [comment]
@MdechampG  I agree with all the comments made. Since I'm a bit short on time,  could you take care of the changes on your end? Thanks :pray:

**Comment by MdechampG** [comment]
> e with all the comments m


Sure !

**Comment by MdechampG** [comment]
> @MdechampG I agree with all the comments made. Since I'm a bit short on time, could you take care of the changes on your end? Thanks 🙏

Sure !

**Review by MdechampG — APPROVED** [review]

**Review by bdeneux — APPROVED** [review]
🤯

**Review by amimart — APPROVED** [review]
🚀

**Pull request merged**
