### PR TITLE
docs: convert images to webp and update readme files

### PR DESCRIPTION
**Pull request by jeremylgn**
self explanatory.

### CODE REVIEW

**Review by fredericvilcot — APPROVED** [review]
Great job @jeremylgn ! 💪

**Review by ccamel — APPROVED** [review]
Great! Thx 😎

**Review by ad2ien — APPROVED** [review]
:+1:

**Comment by ccamel** [comment]
@jeremylgn I suggest that we merge the PR together to check that the deployment is done correctly and that everything is ok for the display of the images.

**Review by amimart — APPROVED** [review]

**Comment by ccamel** [comment]
@jeremylgn you can merge it! ❤️

**Pull request merged**
