### PR TITLE
fix: fix markdown code display on h3

### PR DESCRIPTION
**Pull request by AnjaMis**
This PR fixes the issue mentioned in #262

### CODE REVIEW

**Review by JulienMassonnat — APPROVED** [review]
Work well on Chrome et Firefox. Good job

**Review by fredericvilcot — APPROVED** [review]
😎

**Review by amimart — APPROVED** [review]
I couldn't reproduce the issue on Chrome and Safari, it was working well on my side..

**Review by ccamel — APPROVED** [review]
:pray: thanks

**Pull request merged**
