### PR TITLE
fix(docs): version number broken

### PR DESCRIPTION
**Pull request by bertux**
To fix the error recorded at https://asciinema.org/a/598838.

### CODE REVIEW

**Comment by bertux** [comment]
fix #279

**Comment by ccamel** [comment]
As you noticed, the [CI failed](https://github.com/okp4/docs/actions/runs/5649814717/job/15315636529?pr=278#step:5:9) with the following error:

> Error: The docs folder does not exist for version "5.0.0". A docs folder is expected to be found at commands_versioned_docs/version-5.0.0.

In the context of the fix you want to implement, I think you should modify only the version in the `data/chain.json` resource file and avoid altering `commands_versions.json` file as it is primarily utilized by Docusaurus for handling the versioning of API documentation.

Feel free to reach out to me if you need assistance.

**Review by amimart — CHANGES_REQUESTED** [review]
Hey thx for catching this. I think the matter goes a little further.

In fact, the version referenced in the docker command is the only case the `v` prefix is not needed, by convention regarding docker tags.

But still, this version is referenced in many other places, and this should be managed. Moreover, when a new version is published on the original [okp4d repo](https://github.com/okp4/okp4d), an automation trigger a workflow to update it, see the [bump-okp4d-version.yml](https://github.com/okp4/docs/blob/16280f4fabf73a1493b345988afacae9d82aade3/.github/workflows/bump-okp4d-version.yml) action. This should be considered as well to fix this issue on the long term.

If I can be of any help, maybe I can help and make the needed changes :)

**Comment by bertux** [comment]
thanks @ccamel and @amimart for your feedback, as you explained it's more complicated than it sounded first.
So I will look deeper to see what is really needed.

**Comment by bertux** [comment]
I'm too busy on other things so I let @amimart handle it in a long term way.

**Comment by ccamel** [comment]
Sure. No problem @bertux.

**Pull request closed without merging**
